### ISSUE TITLE
Improuvements

### ISSUE THREAD

**Issue by timofeevboris** [lecram/gifenc#5]
[gifenc.zip](https://github.com/lecram/gifenc/files/2692845/gifenc.zip)

Added new functionality - transparent color index ( > 255 - don't use),
 and local palette (NULL - don't use).
(uint8_t *)(-1)  pointer for palette suppress creating of global palette at call ge_new_gif()

Thank you for a codes.
Best regards!
Enjoy!

**Comment by lecram** [comment]
Hi @timofeevboris,

If you still want me to review these changes, please submit one at a time, preferably as Pull Requests or at least as diff files.

Local palettes are not supported because they make GIFs bigger and are only useful in situations where other file formats (lossy ones) are more suitable.
