### ISSUE TITLE
Creating gif with images

### ISSUE THREAD

**Issue by Ovidy** [lecram/gifenc#7]
Hey there, 
What I'm asking here is not exactly an issue but I want to know, how can I add an image into the frame buffer for creating a gif of images?

Thank you

**Comment by lecram** [comment]
Hi @Ovidy,
Once you have an image in [indexed color format](https://en.wikipedia.org/wiki/Indexed_color) you can just copy it to the buffer at `gif->frame` and then call the function `ge_add_frame()` as described in the README. See also the file `example.c` for reference.
If you don't know how to get your images into the appropriate format, please clarify what's the source/format of your images so that I can further help you. Are you reading the images from files? Which file format?

**Comment by orklann** [comment]
Hi @lecram,

I also has this issue, my image format is PNG, and every pixel in the PNG has R(0-1.0)G(0-1.0)B(0-1.0). How can I convert this type of RGB pixels into indexed color format?

**Comment by orklann** [comment]
It seems I need to get the default palettes table (256 colors) to convert my RGB to indexed color format, but how can I get the default palettes table?

**Comment by orklann** [comment]
Finally it works, I just added a `default_palette` in the `ge_GIF` structure, and copy all requirement palette data into this field in `ge_new_gif()` function, and it works fine. I can now convert my RGB into an color indexed.

Thank you for the elegant GIF library.

**Comment by lecram** [comment]
Hi @orklann!

I'm glad you've found a solution.

I added an option to copy the default palette to a given array. Just use a negative value for the `depth` argument of `ge_new_gif()`.

Instead of calling:

    ge_new_gif(path, w, h, NULL, 8, loop)
Call:

    ge_new_gif(path, w, h, array, -8, loop)
and it will fill `array` with the 256 RGB values.

**Comment by orklann** [comment]
@lecram Thank you for your elegant solution, it does not change the API but still can copy the default palette.
